" Use Vim settings, rather then Vi settings (much better!).
" This must be first, because it changes other options as a side effect.
set nocompatible

" =============== Vundle Initialization ===============
" This loads all the plugins specified in ~/.vim/vundles.vim
" Use Vundle plugin to manage all other plugins
if filereadable(expand("~/.vim/vundles.vim"))
  source ~/.vim/vundles.vim
endif

" ================= Font and Colour ======================

" Set colorscheme, when the terminal has >= 256 colours
if &t_Co >= 256 || has("gui_running")
    set background=dark
    colorscheme hybrid
endif
" Switch syntax highlighting on, when the terminal has colors
if &t_Co > 2 || has("gui_running")
    syntax on
endif

" Font
if has('gui_running')
  set guifont=Source\ Code\ Pro\ 10
endif

" ================ Indentation ======================

set tabstop=4       " Number of visual spaces per TAB
set softtabstop=4   " Number of spaces in TAB when editing
set expandtab       " TABs are spaces
set autoindent
set smartindent
set smarttab
set shiftwidth=2

filetype plugin on
filetype indent on  " Load filetype-specific indent files

" Display tabs and trailing spaces visually
set list listchars=tab:\ \ ,trail:·

set nowrap          " Don't wrap lines
set linebreak       " Wrap lines at convenient points

" Set indentation to 8 for assembly languages
autocmd FileType asm setlocal shiftwidth=8 tabstop=8

" ================ User Interface ====================

set number          " Show number lines
set laststatus=2    " Turn on Status bar
set showcmd         " Show command in bottom bar
set showmode        " Show current mode in bottom bar
set cursorline      " Highlight current line
set lazyredraw      " Redraw only when we need to
set showmatch       " Highlight matching [{()}]
if has('gui_running')
  set guioptions-=T   " Remove toolbar from GVim
endif

let g:airline_powerline_fonts = 1       "Powerline font

" ================ Search ===========================

set incsearch       " Search as characters are entered
set hlsearch        " Highlight matches
set ignorecase      " Ignore case when searching...
set smartcase       " ...unless we type a capital
" Turn off search highlight
nnoremap <leader><space> :nohlsearch<CR>

" ================ Folds ============================

set foldenable          " Enable folding
set foldlevelstart=10   " Open most folds by default
set foldnestmax=3       " 10 nested fold max
set foldmethod=indent   " Fold based on indent level
" Space open/closes folds
nnoremap <space> za

" ================ Movement ==========================

" Move vertically by visual line
nnoremap j gj
nnoremap k gk
" Highlight last inserted text
nnoremap gV '[v']

" ================ Leader Shortcuts ==================

" Change leader to a comma because the backslash is too far away
" That means all \x commands turn into ,x
" The mapleader has to be set before vundle starts loading all
" the plugins.
let mapleader=","

" Toggle Gundo (undo tree)
nnoremap <leader>u :GundoToggle<CR>

" Edit vimrc/bashrc and load vimrc bindings
nnoremap <leader>ev :vsp $MYVIMRC<CR>
nnoremap <leader>eb :vsp ~/.bashrc<CR>
nnoremap <leader>ez :vsp $ZDITDIR/.zshrc<CR>
nnoremap <leader>sv :source $MYVIMRC<CR>

" Save session
nnoremap <leader>s :mksessrion<CR>

" ================ General Config ====================

set backspace=indent,eol,start  "Allow backspace in insert mode
set history=1000                "Store lots of :cmdline history
set gcr=a:blinkon0              "Disable cursor blink
set visualbell                  "No sounds
set autoread                    "Reload files changed outside vim

" This makes vim act like all other editors, buffers can
" exist in the background without being in a window.
" http://items.sjbach.com/319/configuring-vim-right
set hidden

" ================ Turn Off Swap Files ==============

set noswapfile
set nobackup
set nowb

" ================ Persistent Undo ==================
" Keep undo history across sessions, by storing in file.
" Only works all the time.
if has('persistent_undo')
  silent !mkdir ~/.vim/backups > /dev/null 2>&1
  set undodir=~/.vim/backups
  set undofile
endif

" ================ Completion =======================

set wildmode=list:longest
set wildmenu                "enable ctrl-n and ctrl-p to scroll thru matches
set wildignore=*.o,*.obj,*~ "stuff to ignore when tab completing
set wildignore+=*vim/backups*
set wildignore+=*sass-cache*
set wildignore+=*DS_Store*
set wildignore+=vendor/rails/**
set wildignore+=vendor/cache/**
set wildignore+=*.gem
set wildignore+=log/**
set wildignore+=tmp/**
set wildignore+=*.png,*.jpg,*.gif

"
" ================ Scrolling ========================

set scrolloff=8         "Start scrolling when we're 8 lines away from margins
set sidescrolloff=15
set sidescroll=1


